# Generated by Django 4.2.11 on 2024-03-30 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpagedata",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mainpagedata",
            name="tel_no",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
