# Generated by Django 4.2.11 on 2024-03-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildings", "0002_mainpagedata_email_mainpagedata_tel_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectsDone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_url", models.CharField(max_length=1280)),
                ("text", models.TextField(max_length=500)),
            ],
        ),
    ]
